version: '3'

services:
    node:
        container_name: react-dev
        image: react-dev:latest
        build:
            context: .
        volumes:
            - .:/usr/src/app
        command: sh -c "npm start"
        ports:
            - "3001:3000"