version: '3'

services:
    app:
        container_name: reactapp
        image: reactapp:latest
        build:
            context: .
            args:
              - NODE_TAG=12.6
              - NGINX_TAG=alpine
        environment:
            - NODE_ENV=production

        ports:
            - 8081:80
        restart: always