#!/bin/sh

# See if the environment variables for java home are set
# in the path and try to figure it out.
if test ! -f "${OPENDJ_JAVA_BIN}"
then
  if test ! -d "${OPENDJ_JAVA_HOME}"
  then
    if test ! -f "${OPENDS_JAVA_BIN}"
    then
      if test ! -d "${OPENDS_JAVA_HOME}"
  then
    TEMP="/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"
    if test -f "${TEMP}"
    then
      OPENDJ_JAVA_BIN="${TEMP}"
      export OPENDJ_JAVA_BIN
    fi
      else
        OPENDJ_JAVA_BIN="${OPENDS_JAVA_HOME}/bin/java"
        export OPENDJ_JAVA_BIN
      fi
    else
      OPENDJ_JAVA_BIN="${OPENDS_JAVA_BIN}"
      export OPENDJ_JAVA_BIN
    fi
  else
    OPENDJ_JAVA_BIN="${OPENDJ_JAVA_HOME}/bin/java"
    export OPENDJ_JAVA_BIN
  fi
fi


# See if the environment variables for arguments are set.
if test -z "${OPENDJ_JAVA_ARGS}"
then
  if test -z "${OPENDS_JAVA_ARGS}"
  then
    if test "${SCRIPT_NAME}.java-args" = "ldapcompare.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "dsreplication.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "upgrade.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "base64.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "start-ds.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "ldifmodify.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "backup.offline.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "manage-account.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "backup.online.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "ldapsearch.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "restore.online.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "export-ldif.offline.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "setup.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "encode-password.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "make-ldif.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "control-panel.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms64m -Xmx128m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "manage-tasks.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "stop-ds.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "restore.offline.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "ldapmodify.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "uninstall.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "ldif-diff.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "import-ldif.offline.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "ldapdelete.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "dsreplication.offline.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "create-rc-script.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "rebuild-index.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "export-ldif.online.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "import-ldif.online.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "backendstat.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "ldappasswordmodify.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "dsconfig.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "status.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "ldifsearch.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "verify-index.java-args"
    then
      OPENDJ_JAVA_ARGS="-server"
      export OPENDJ_JAVA_ARGS
    elif test "${SCRIPT_NAME}.java-args" = "list-backends.java-args"
    then
      OPENDJ_JAVA_ARGS="-Xms8m -client"
      export OPENDJ_JAVA_ARGS
    fi
  else
    OPENDJ_JAVA_ARGS=${OPENDS_JAVA_ARGS}
    export OPENDJ_JAVA_ARGS
  fi
fi

